services:
  datagen:
    build:
      context: ..
      dockerfile: datagen/Dockerfile
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.13-slim}
    image: nanochat-datagen:latest
    container_name: nanochat-datagen
    environment:
      # OpenRouter credentials and metadata
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODELS=${OPENROUTER_MODELS:-}
      - OPENROUTER_REFERRER=${OPENROUTER_REFERRER:-BRADDLEZ}
      - OPENROUTER_TITLE=${OPENROUTER_TITLE:-OOGA}
      # Dataset targets
      - SFT_TARGET=${SFT_TARGET:-0}
      - DPO_TARGET=${DPO_TARGET:-0}
      - DATAGEN_POLL_SECS=${DATAGEN_POLL_SECS:-15}
      # Automatic increments per poll when no remaining target work
      - SFT_INCREMENT=${SFT_INCREMENT:-2}
      - DPO_INCREMENT=${DPO_INCREMENT:-2}
      # Base dir for datasets (mounted volume)
      - NANOCHAT_BASE_DIR=/data
      # Server options
      - HOST=0.0.0.0
      - PORT=8981
      # Parallel workers
      - WORKERS=${WORKERS:-5}
      - REDIS_URL=${REDIS_URL}
    # For local testing, uncomment to expose the service
    # ports:
    #   - "8981:8981"
    volumes:
      - datagen_data:/data
    restart: unless-stopped

  celery-worker:
    build:
      context: ..
      dockerfile: datagen/Dockerfile
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.13-slim}
    image: nanochat-datagen:latest
    container_name: nanochat-datagen-worker
    depends_on:
      - datagen
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODELS=${OPENROUTER_MODELS:-}
      - OPENROUTER_REFERRER=${OPENROUTER_REFERRER:-BRADDLEZ}
      - OPENROUTER_TITLE=${OPENROUTER_TITLE:-OOGA}
      - REDIS_URL=${REDIS_URL}
      - PORT=8981
      - CELERY_CONCURRENCY=${CELERY_CONCURRENCY:-4}
      - CELERY_INSTANCES=${CELERY_INSTANCES:-5}
    command: sh -c '
      inst="${CELERY_INSTANCES:-5}"; case "$inst" in ''|*[!0-9]*) inst=5 ;; esac;
      conc="${CELERY_CONCURRENCY:-4}"; case "$conc" in ''|*[!0-9]*) conc=4 ;; esac;
      i=1;
      while [ "$i" -le "$inst" ]; do
        echo "Starting Celery worker $i/$inst with concurrency $conc";
        celery -A datagen.celery_app.celery_app worker --loglevel=INFO --concurrency="$conc" --hostname="%h-w$i" &
        i=$((i+1));
      done;
      wait'
    restart: unless-stopped

volumes:
  datagen_data:
    driver: local


